### ISSUE TITLE
Some zip codes do not geocode correctly

### ISSUE THREAD

**Issue by aeyates** [matthewj301/site-stalker#3]
Without country context, some zip codes geocode to the wrong location. For example, the zip code for Cambridge, MA is 02138, but geocode gives the location as "Деснянський район, Київ, Київська міська громада, 02138, Україна"

The fix is to include country information when geocoding (e.g. self.geocoder.geocode(vax_site_zip_code, country_codes=['US']). I can submit a pull request shortly.

Thanks for this great project.

**Comment by matthewj301** [comment]
Great catch, I'll merge it. Thanks for finding this!
